// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FeedKitchen.Entities.Models;

public partial class Fixing
{
    public long Id { get; set; }

    public string Title { get; set; }

    public string Url { get; set; }

    public long AuthorName { get; set; }

    public long AuthorEmail { get; set; }

    public DateTime PublishingDate { get; set; }

    public string Content { get; set; }

    public string Summary { get; set; }

    public long IngredientId { get; set; }

    public virtual ICollection<Category> Categories { get; set; } = new List<Category>();

    public virtual Ingredient Ingredient { get; set; }
}