// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FeedKitchen.Entities.Models;

public partial class Ingredient
{
    public long Id { get; set; }

    public string Name { get; set; }

    public string Url { get; set; }

    public long RecipeId { get; set; }

    public virtual ICollection<Fixing> Fixings { get; set; } = new List<Fixing>();

    public virtual Recipe Recipe { get; set; }
}