<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CodeHollow.FeedReader" />
    <PackageReference Include="FluentAssertions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FeedKitchen.ServiceDefaults\FeedKitchen.ServiceDefaults.csproj" />
    <ProjectReference Include="..\FeedKitchen.Shared\FeedKitchen.Shared.csproj" />
    <ProjectReference Include="..\FeedKitchen.Repositories\FeedKitchen.Repositories.csproj" />
  </ItemGroup>

</Project>
