FROM mcr.microsoft.com/dotnet/sdk:6.0-focal as builder
ADD ../FeedKitchen.Repositories /FeedKitchen.Repositories
ADD ../FeedKitchen.Shared /FeedKitchen.Shared
ADD ../FeedKitchen.ChefPortal /FeedKitchen.ChefPortal
RUN ["dotnet", "publish", "-o", "/build", "./FeedKitchen.ChefPortal"]


FROM mcr.microsoft.com/dotnet/sdk:6.0-focal
COPY --from=builder /build /app
WORKDIR /app
EXPOSE 5002 5002
ENV ASPNETCORE_URLS=https://+:5002
ENTRYPOINT ["dotnet", "FeedKitchen.ChefPortal.dll"]