FROM mcr.microsoft.com/dotnet/sdk:6.0-focal as builder
ADD ../FeedKitchen.Doorman /FeedKitchen.Doorman
RUN ["dotnet", "publish", "-o", "/build", "./FeedKitchen.Doorman"]


FROM mcr.microsoft.com/dotnet/sdk:6.0-focal
COPY --from=builder /build /app
WORKDIR /app
EXPOSE 5000 5000
ENV ASPNETCORE_URLS=https://+:5000
ENTRYPOINT ["dotnet", "FeedKitchen.Doorman.dll"]