FROM mcr.microsoft.com/dotnet/sdk:6.0-focal as builder
ADD ../FeedKitchen.Repositories /FeedKitchen.Repositories
ADD ../FeedKitchen.Shared /FeedKitchen.Shared
ADD ../FeedKitchen.MenuWaiter /FeedKitchen.MenuWaiter
RUN ["dotnet", "publish", "-o", "/build", "./FeedKitchen.MenuWaiter"]


FROM mcr.microsoft.com/dotnet/sdk:6.0-focal
COPY --from=builder /build /app
WORKDIR /app
EXPOSE 5001 5001
ENV ASPNETCORE_URLS=https://+:5001
ENTRYPOINT ["dotnet", "FeedKitchen.MenuWaiter.dll"]